### ISSUE TITLE
Error trying to download VIA definitions

### ISSUE THREAD

**Issue by MycroftHolmes1989** [vial-kb/vial-gui#133]
Whenever I try to download VIA definitions, I get the following error:

```
Traceback (most recent call last):
  File "urllib/request.py", line 1349, in do_open
  File "http/client.py", line 1291, in request
  File "http/client.py", line 1337, in _send_request
  File "http/client.py", line 1286, in endheaders
  File "http/client.py", line 1046, in _send_output
  File "http/client.py", line 984, in send
  File "http/client.py", line 1444, in connect
  File "http/client.py", line 956, in connect
  File "socket.py", line 704, in create_connection
  File "socket.py", line 745, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "main_window.py", line 318, in load_via_stack_json
  File "urllib/request.py", line 223, in urlopen
  File "urllib/request.py", line 532, in open
  File "urllib/request.py", line 642, in http_response
  File "urllib/request.py", line 564, in error
  File "urllib/request.py", line 504, in _call_chain
  File "urllib/request.py", line 756, in http_error_302
  File "urllib/request.py", line 526, in open
  File "urllib/request.py", line 544, in _open
  File "urllib/request.py", line 504, in _call_chain
  File "urllib/request.py", line 1392, in https_open
  File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

```

OS: Ubuntu 22.04.1
Python version: Python 3.10.4

**Comment by MycroftHolmes1989** [comment]
Reason: My ISP has banned githubusercontent.com. Closed.
